package com.skillswap.enums;

public enum NotificationType {
    EXCHANGE_RECEIVED,
    EXCHANGE_ACCEPTED,
    EXCHANGE_REJECTED,
    EXCHANGE_CANCELLED,
    SESSION_SCHEDULED,
    SESSION_UPDATED,
    SESSION_COMPLETED,
    SESSION_CANCELLED
}
